config/routes.rb
Rails.application.routes.draw do
  resources :google_songs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/google_song.rb
class GoogleSong < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/google_songs_controller.rb
class GoogleSongsController < ApplicationController
  before_action :set_google_song, only: [:show, :edit, :update, :destroy]

  # GET /google_songs
  # GET /google_songs.json
  def index
    @google_songs = GoogleSong.all
  end

  # GET /google_songs/1
  # GET /google_songs/1.json
  def show
  end

  # GET /google_songs/new
  def new
    @google_song = GoogleSong.new
  end

  # GET /google_songs/1/edit
  def edit
  end

  # POST /google_songs
  # POST /google_songs.json
  def create
    @google_song = GoogleSong.new(google_song_params)

    respond_to do |format|
      if @google_song.save
        format.html { redirect_to @google_song, notice: 'Google song was successfully created.' }
        format.json { render :show, status: :created, location: @google_song }
      else
        format.html { render :new }
        format.json { render json: @google_song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /google_songs/1
  # PATCH/PUT /google_songs/1.json
  def update
    respond_to do |format|
      if @google_song.update(google_song_params)
        format.html { redirect_to @google_song, notice: 'Google song was successfully updated.' }
        format.json { render :show, status: :ok, location: @google_song }
      else
        format.html { render :edit }
        format.json { render json: @google_song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /google_songs/1
  # DELETE /google_songs/1.json
  def destroy
    @google_song.destroy
    respond_to do |format|
      format.html { redirect_to google_songs_url, notice: 'Google song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_google_song
      @google_song = GoogleSong.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def google_song_params
      params.require(:google_song).permit(:Artise, :product_title, :content_provider, :device_type, :label, :start_date, :end_date, :year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/google_songs_helper.rb
module GoogleSongsHelper
end

app/views/google_songs/_form.html.erb
<%= form_with(model: google_song, local: true) do |form| %>
  <% if google_song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(google_song.errors.count, "error") %> prohibited this google_song from being saved:</h2>

      <ul>
      <% google_song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Artise %>
    <%= form.text_field :Artise %>
  </div>

  <div class="field">
    <%= form.label :product_title %>
    <%= form.text_field :product_title %>
  </div>

  <div class="field">
    <%= form.label :content_provider %>
    <%= form.text_field :content_provider %>
  </div>

  <div class="field">
    <%= form.label :device_type %>
    <%= form.text_field :device_type %>
  </div>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.text_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.text_field :end_date %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/google_songs/edit.html.erb
<h1>Editing Google Song</h1>

<%= render 'form', google_song: @google_song %>

<%= link_to 'Show', @google_song %> |
<%= link_to 'Back', google_songs_path %>

app/views/google_songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Google Songs</h1>

<table>
  <thead>
    <tr>
      <th>Artise</th>
      <th>Product title</th>
      <th>Content provider</th>
      <th>Device type</th>
      <th>Label</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @google_songs.each do |google_song| %>
      <tr>
        <td><%= google_song.Artise %></td>
        <td><%= google_song.product_title %></td>
        <td><%= google_song.content_provider %></td>
        <td><%= google_song.device_type %></td>
        <td><%= google_song.label %></td>
        <td><%= google_song.start_date %></td>
        <td><%= google_song.end_date %></td>
        <td><%= google_song.year %></td>
        <td><%= link_to 'Show', google_song %></td>
        <td><%= link_to 'Edit', edit_google_song_path(google_song) %></td>
        <td><%= link_to 'Destroy', google_song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Google Song', new_google_song_path %>

app/views/google_songs/new.html.erb
<h1>New Google Song</h1>

<%= render 'form', google_song: @google_song %>

<%= link_to 'Back', google_songs_path %>

app/views/google_songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artise:</strong>
  <%= @google_song.Artise %>
</p>

<p>
  <strong>Product title:</strong>
  <%= @google_song.product_title %>
</p>

<p>
  <strong>Content provider:</strong>
  <%= @google_song.content_provider %>
</p>

<p>
  <strong>Device type:</strong>
  <%= @google_song.device_type %>
</p>

<p>
  <strong>Label:</strong>
  <%= @google_song.label %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @google_song.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @google_song.end_date %>
</p>

<p>
  <strong>Year:</strong>
  <%= @google_song.year %>
</p>

<%= link_to 'Edit', edit_google_song_path(@google_song) %> |
<%= link_to 'Back', google_songs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NjoTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>